---
- hosts: all
  become: true
  tasks:
    - name: copy html file
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
 