---
- hosts: all
  become: true
  tasks:
    - name: install gpg
      apt:
        name: gnupg,software-properties-common
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: add gpg key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        validate_certs: no

    - name: add grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        validate_certs: no

    - name: install grafana
      apt:
        name: grafana
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: start grafana server
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: wait for service up
      uri:
        url: "http://127.0.0.1:3000"
        status_code: 200
      register: __result
      until: __result.status == 200
      retries: 120
      delay: 1

    - name: Configure Grafana to listen only on localhost
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^#?http_addr ='
        line: 'http_addr = 127.0.0.1'

    - name: allow prometheus necessary port
      ufw:
        rule: allow
        port: 9090
        proto: tcp

    - name: restart Grafana service
      service:
        name: grafana-server
        state: restarted