---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (Ubuntu)
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

  roles:
    - update_and_upgrade_packages