- name: Install Caddy PPA
  apt_repository:
    repo: 'deb [trusted=yes] https://apt.fury.io/caddy/ /'
    state: present
    update_cache: yes

- name: install Caddy
  apt:
    name: caddy
    state: present

- name: create Caddyfile from template
  template:
    src: caddyfile.j2
    dest: /etc/caddy/Caddyfile

- name: ensure Caddy service is started and enabled
  systemd:
    name: caddy
    state: started
    enabled: yes